# Generated by Django 2.2.12 on 2020-06-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWorks', '0002_auto_20200611_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workID', models.IntegerField()),
                ('character', models.CharField(max_length=45)),
                ('cast', models.CharField(max_length=45)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workID', models.IntegerField()),
                ('editPro', models.BooleanField(default=False)),
                ('illustPro', models.BooleanField(default=False)),
                ('animaPro', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='works',
            name='animator',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='works',
            name='editor',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='works',
            name='illustrator',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='works',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='works',
            name='writer',
            field=models.CharField(max_length=45),
        ),
    ]
