# Generated by Django 2.2.12 on 2020-06-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('place', models.IntegerField()),
                ('human', models.TextField(max_length=45)),
                ('money', models.DecimalField(decimal_places=0, max_digits=10)),
                ('hour', models.IntegerField()),
                ('money_1hour', models.IntegerField()),
                ('payoff', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.IntegerField()),
                ('place', models.IntegerField()),
                ('content', models.IntegerField()),
                ('work_id', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('money', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('blance', models.IntegerField()),
                ('human', models.TextField(max_length=45)),
                ('money', models.DecimalField(decimal_places=0, max_digits=10)),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
                ('paymentNo', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
