# Generated by Django 2.2.12 on 2020-06-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMoney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='note',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
