# Generated by Django 2.2.12 on 2020-06-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMoney', '0003_auto_20200611_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='human',
        ),
        migrations.RemoveField(
            model_name='pos',
            name='human',
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='pos',
            name='user',
            field=models.CharField(default='', max_length=45),
        ),
    ]
