# Generated by Django 2.2.12 on 2020-06-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMoney', '0004_auto_20200612_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='hour',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payment_detail',
            name='hour',
            field=models.FloatField(),
        ),
    ]
