# Generated by Django 2.2.14 on 2020-07-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appChat', '0002_auto_20200726_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='check',
            new_name='checkBool',
        ),
    ]
