# Generated by Django 2.2.14 on 2020-07-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appChat', '0003_auto_20200726_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='userEnglish',
            field=models.CharField(default='', max_length=45),
        ),
    ]
