# Generated by Django 2.2.14 on 2020-07-28 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appChat', '0009_auto_20200728_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploadplace',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg', 'm4a'])]),
        ),
    ]
